apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingdom-check-certificates
  namespace: kube-system
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 10
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          containers:
          - name: pingdom-check-certificates
            image: previousnext/pingdom-check-certificates:v0.0.1
            imagePullPolicy: Always
            env:
            - name:  SLACK_CHANNEL_READY
              value: ""
            - name:  SLACK_CHANNEL_NOT_READY
              value: ""
            - name:  SLACK_TOKEN
              value: ""
            - name:  PINGDOM_USER
              value: ""
            - name:  PINGDOM_PASS
              value: ""
            - name:  PINGDOM_TOKEN
              value: ""